# docker-compose.yml

version: "3"

services:
  site-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: site-dev
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000